# Numpy Init 

In [2]:
#importation de la bibliotheque
import numpy as np


In [3]:
a=np.array([1,2,3])
a

array([1, 2, 3])

contructeur numpy

In [4]:
# np.zeros to fill all table with 0 as a tuple
B = np.zeros((4,5))
B

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
# np.ones to fill all table with 1 as a tuple
C = np.ones((4,5))
C

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
# np.full to fill all table with value pass as second argument  as a tuple
D = np.full((4,5), 45)
D

array([[45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45]])

In [7]:
np.random.randn(4,5)

array([[-0.84841383, -0.28086616,  1.07019656,  0.00604225, -0.26609209],
       [-0.34394584,  1.2959903 , -0.76215116,  0.27660964,  0.40196798],
       [ 2.60655261, -0.49651306, -1.62043357,  1.12260232, -2.55134165],
       [-0.48340197,  0.40262125,  0.38310974, -1.04260684,  1.46829391]])

In [8]:
# pour fixer le random we use seed()
np.random.seed(0)
np.random.randn(4,5)

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799],
       [-0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ],
       [ 0.14404357,  1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 , -0.85409574]])