# Numpy Init 

In [2]:
#importation de la bibliotheque
import numpy as np


In [3]:
a=np.array([1,2,3])
a

array([1, 2, 3])

contructeur numpy

In [4]:
# np.zeros to fill all table with 0 as a tuple
B = np.zeros((4,5))
B

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
# np.ones to fill all table with 1 as a tuple
C = np.ones((4,5))
C

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
# np.full to fill all table with value pass as second argument  as a tuple
D = np.full((4,5), 45)
D

array([[45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45]])